set_property(GLOBAL PROPERTY USE_FOLDERS ON)
set_property(GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER "CMake")

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_DEBUG_POSTFIX "_d")

set(GLFW_BUILD_EXAMPLES OFF CACHE INTERNAL "Build the GLFW example programs")
set(GLFW_BUILD_TESTS OFF CACHE INTERNAL "Build the GLFW test programs")
set(GLFW_BUILD_DOCS OFF CACHE INTERNAL "Build the GLFW documentation")
set(GLFW_INSTALL OFF CACHE INTERNAL "Generate the GLFW install target")
if(UNIX AND NOT APPLE)
  set(GLFW_BUILD_X11 ON CACHE INTERNAL "Build GLFW with X11 support")
  set(GLFW_BUILD_WAYLAND OFF CACHE INTERNAL "Disable the unused Wayland backend")
endif()
set(SPDLOG_BUILD_EXAMPLE OFF CACHE INTERNAL "Build spdlog examples")
set(SPDLOG_BUILD_TESTS OFF CACHE INTERNAL "Build spdlog tests")
set(SPDLOG_INSTALL OFF CACHE INTERNAL "Generate the spdlog install target")
set(BUILD_SHARED_LIBS OFF CACHE INTERNAL "Build dependencies as static libraries")
set(ASSIMP_WARNINGS_AS_ERRORS OFF CACHE INTERNAL "Do not promote Assimp warnings")
set(ASSIMP_BUILD_ASSIMP_TOOLS OFF CACHE INTERNAL "Build Assimp command-line tools")
set(ASSIMP_BUILD_SAMPLES OFF CACHE INTERNAL "Build Assimp samples")
set(ASSIMP_BUILD_TESTS OFF CACHE INTERNAL "Build Assimp tests")
set(ASSIMP_INSTALL OFF CACHE INTERNAL "Generate the Assimp install target")
set(ASSIMP_NO_EXPORT ON CACHE INTERNAL "Disable Assimp exporters")
set(ASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT OFF CACHE INTERNAL "Disable unused Assimp importers")
set(ASSIMP_BUILD_OBJ_IMPORTER ON CACHE INTERNAL "Enable OBJ importer")
set(ASSIMP_BUILD_GLTF_IMPORTER ON CACHE INTERNAL "Enable glTF importer")
set(ASSIMP_BUILD_FBX_IMPORTER ON CACHE INTERNAL "Enable FBX importer")

function(openglgp_enable_warnings target)
  if(MSVC)
    target_compile_options(${target} PRIVATE /W4 /permissive-)
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
  endif()
endfunction()